# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(963, 704)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.msaOutputText_2 = QtWidgets.QTextBrowser(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.msaOutputText_2.setFont(font)
        self.msaOutputText_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.msaOutputText_2.setObjectName("msaOutputText_2")
        self.gridLayout_5.addWidget(self.msaOutputText_2, 5, 0, 1, 3)
        self.resultBtn_4 = QtWidgets.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resultBtn_4.setFont(font)
        self.resultBtn_4.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.resultBtn_4.setObjectName("resultBtn_4")
        self.gridLayout_5.addWidget(self.resultBtn_4, 6, 2, 1, 1)
        self.browseBtn_5 = QtWidgets.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseBtn_5.setFont(font)
        self.browseBtn_5.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.browseBtn_5.setObjectName("browseBtn_5")
        self.gridLayout_5.addWidget(self.browseBtn_5, 3, 0, 1, 1)
        self.browseBtn_4 = QtWidgets.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseBtn_4.setFont(font)
        self.browseBtn_4.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.browseBtn_4.setObjectName("browseBtn_4")
        self.gridLayout_5.addWidget(self.browseBtn_4, 1, 0, 2, 1)
        self.filepathView_5 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.filepathView_5.setFont(font)
        self.filepathView_5.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.filepathView_5.setObjectName("filepathView_5")
        self.gridLayout_5.addWidget(self.filepathView_5, 3, 1, 1, 2)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_4, 0, 0, 1, 3)
        self.filepathView_4 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.filepathView_4.setFont(font)
        self.filepathView_4.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.filepathView_4.setObjectName("filepathView_4")
        self.gridLayout_5.addWidget(self.filepathView_4, 1, 1, 2, 2)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.graphicsView = PlotWidget(self.tab_3)
        self.graphicsView.setStyleSheet("color: rgb(0, 0, 0);")
        self.graphicsView.setObjectName("graphicsView")
        ##
        self.graphicsView.hideAxis('bottom')
        self.graphicsView.hideAxis('left')
        self.graphicsView.setBackground("w")
        ##
        self.gridLayout_4.addWidget(self.graphicsView, 2, 2, 2, 2)
        self.resultBtn_3 = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resultBtn_3.setFont(font)
        self.resultBtn_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.resultBtn_3.setObjectName("resultBtn_3")
        self.gridLayout_4.addWidget(self.resultBtn_3, 4, 3, 1, 1)
        self.msaOutputText = QtWidgets.QTextBrowser(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.msaOutputText.setFont(font)
        self.msaOutputText.setStyleSheet("color: rgb(0, 0, 0);")
        self.msaOutputText.setObjectName("msaOutputText")
        self.gridLayout_4.addWidget(self.msaOutputText, 2, 0, 1, 2)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_3, 0, 1, 1, 3)
        self.filepathView_3 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.filepathView_3.setFont(font)
        self.filepathView_3.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.filepathView_3.setObjectName("filepathView_3")
        self.gridLayout_4.addWidget(self.filepathView_3, 1, 1, 1, 3)
        self.browseBtn_3 = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseBtn_3.setFont(font)
        self.browseBtn_3.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.browseBtn_3.setObjectName("browseBtn_3")
        self.gridLayout_4.addWidget(self.browseBtn_3, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textLabel = QtWidgets.QLabel(self.tab)
        self.textLabel.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textLabel.setFont(font)
        self.textLabel.setStyleSheet("")
        self.textLabel.setObjectName("textLabel")
        self.gridLayout_2.addWidget(self.textLabel, 2, 0, 1, 1)
        self.inputTextView = QtWidgets.QPlainTextEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(14)
        self.inputTextView.setFont(font)
        self.inputTextView.setStyleSheet("color: rgb(0, 0, 0);")
        self.inputTextView.setObjectName("inputTextView")
        self.gridLayout_2.addWidget(self.inputTextView, 4, 0, 1, 3)
        self.resultBtn = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resultBtn.setFont(font)
        self.resultBtn.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.resultBtn.setObjectName("resultBtn")
        self.gridLayout_2.addWidget(self.resultBtn, 5, 2, 1, 1)
        self.textLabel_2 = QtWidgets.QLabel(self.tab)
        self.textLabel_2.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textLabel_2.setFont(font)
        self.textLabel_2.setStyleSheet("")
        self.textLabel_2.setObjectName("textLabel_2")
        self.gridLayout_2.addWidget(self.textLabel_2, 5, 0, 1, 1)
        self.outputTextView = QtWidgets.QTextBrowser(self.tab)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.outputTextView.setFont(font)
        self.outputTextView.setStyleSheet("color: rgb(0, 0, 0);")
        self.outputTextView.setObjectName("outputTextView")
        self.gridLayout_2.addWidget(self.outputTextView, 6, 0, 1, 3)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"color: rgb(0, 0, 0);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 2, 1, 1, 2)
        self.browseBtn = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.browseBtn.setFont(font)
        self.browseBtn.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(65, 65, 195);")
        self.browseBtn.setObjectName("browseBtn")
        self.gridLayout_2.addWidget(self.browseBtn, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.resultBtn_2 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resultBtn_2.setFont(font)
        self.resultBtn_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.resultBtn_2.setObjectName("resultBtn_2")
        self.gridLayout_3.addWidget(self.resultBtn_2, 4, 2, 1, 1)
        self.textLabel_4 = QtWidgets.QLabel(self.tab_2)
        self.textLabel_4.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textLabel_4.setFont(font)
        self.textLabel_4.setStyleSheet("")
        self.textLabel_4.setObjectName("textLabel_4")
        self.gridLayout_3.addWidget(self.textLabel_4, 4, 0, 1, 1)
        self.textLabel_3 = QtWidgets.QLabel(self.tab_2)
        self.textLabel_3.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textLabel_3.setFont(font)
        self.textLabel_3.setStyleSheet("\n"
"")
        self.textLabel_3.setObjectName("textLabel_3")
        self.gridLayout_3.addWidget(self.textLabel_3, 0, 0, 1, 1)
        self.extractBtn = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.extractBtn.setFont(font)
        self.extractBtn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.extractBtn.setObjectName("extractBtn")
        self.gridLayout_3.addWidget(self.extractBtn, 6, 1, 1, 1)
        self.outputTextView_2 = QtWidgets.QTextBrowser(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.outputTextView_2.setFont(font)
        self.outputTextView_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.outputTextView_2.setObjectName("outputTextView_2")
        self.gridLayout_3.addWidget(self.outputTextView_2, 5, 0, 1, 3)
        self.inputTextView_2 = QtWidgets.QPlainTextEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(14)
        self.inputTextView_2.setFont(font)
        self.inputTextView_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.inputTextView_2.setObjectName("inputTextView_2")
        self.gridLayout_3.addWidget(self.inputTextView_2, 3, 0, 1, 3)
        self.browseBtn_2 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.browseBtn_2.setFont(font)
        self.browseBtn_2.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"background-color: rgb(65, 65, 195);\n"
"color: rgb(255, 255, 255);")
        self.browseBtn_2.setObjectName("browseBtn_2")
        self.gridLayout_3.addWidget(self.browseBtn_2, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 2)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(3, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(4, "")
        self.gridLayout_3.addWidget(self.comboBox_2, 0, 1, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.resultBtn_4.setText(_translate("MainWindow", "Result"))
        self.browseBtn_5.setText(_translate("MainWindow", "File"))
        self.browseBtn_4.setText(_translate("MainWindow", "File"))
        self.filepathView_5.setText(_translate("MainWindow", "---"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Choose Method"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Global Alignment"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Local Alignment"))
        self.filepathView_4.setText(_translate("MainWindow", "---"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Pairwise Sequence Alignment"))
        self.resultBtn_3.setText(_translate("MainWindow", "Result"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Choose Method"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Sequence Alignment"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Phylogenetic Tree"))
        self.filepathView_3.setText(_translate("MainWindow", "---"))
        self.browseBtn_3.setText(_translate("MainWindow", "File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Multiple Sequence Alignment"))
        self.textLabel.setText(_translate("MainWindow", "Text or a file"))
        self.resultBtn.setText(_translate("MainWindow", "Result"))
        self.textLabel_2.setText(_translate("MainWindow", "Output"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Choose Type"))
        self.comboBox.setItemText(1, _translate("MainWindow", "DNA"))
        self.comboBox.setItemText(2, _translate("MainWindow", "RNA"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Protein"))
        self.browseBtn.setText(_translate("MainWindow", "File"))
        self.label.setText(_translate("MainWindow", "---"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Calculations"))
        self.resultBtn_2.setText(_translate("MainWindow", "Result"))
        self.textLabel_4.setText(_translate("MainWindow", "Output"))
        self.textLabel_3.setText(_translate("MainWindow", "Text or a file"))
        self.extractBtn.setText(_translate("MainWindow", "Extract File"))
        self.browseBtn_2.setText(_translate("MainWindow", "File"))
        self.label_2.setText(_translate("MainWindow", "---"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Choose Method"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Transcribe"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Translate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Conversions"))

from pyqtgraph import PlotWidget
